FROM python:3.8

WORKDIR /code-ws

COPY requirements.txt .

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

COPY src/chatsocket.py .

EXPOSE 5000

ENTRYPOINT [ "python3" ]

CMD ["chatsocket.py"]
