"""zombies user_id index

Revision ID: 51d5c69f5a8e
Revises: b1529b9f5e15
Create Date: 2026-08-10 15:48:56.250272

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d5c69f5a8e'
down_revision: Union[str, None] = 'b1529b9f5e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_zombies_user', 'zombies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zombies_user', table_name='zombies')
    # ### end Alembic commands ###

