"""initial schema

Revision ID: b1529b9f5e15
Revises: 
Create Date: 2026-08-10 15:11:14.671226

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1529b9f5e15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('proctype', sa.String(length=64), nullable=False),
    sa.Column('ts_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completions_proctype'), 'completions', ['proctype'], unique=False)
    op.create_index(op.f('ix_completions_timestamp'), 'completions', ['timestamp'], unique=False)
    op.create_table('rating_archive',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key_date', sa.String(length=10), nullable=False),
    sa.Column('table_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('kind', 'key_date')
    )
    op.create_table('riddles',
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('riddle_json', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'locale')
    )
    op.create_table('robots',
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('locale', 'level')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=False),
    sa.Column('inactive', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('image_blob', sa.LargeBinary(), nullable=True),
    sa.Column('account', sa.String(length=256), nullable=True),
    sa.Column('plan', sa.String(length=64), nullable=True),
    sa.Column('nick_lc', sa.String(length=128), nullable=True),
    sa.Column('name_lc', sa.String(length=256), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('ready_timed', sa.Boolean(), nullable=False),
    sa.Column('chat_disabled', sa.Boolean(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('human_elo', sa.Integer(), nullable=False),
    sa.Column('manual_elo', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=False),
    sa.Column('highest_score_game', sa.String(length=64), nullable=True),
    sa.Column('best_word', sa.String(length=64), nullable=True),
    sa.Column('best_word_score', sa.Integer(), nullable=False),
    sa.Column('best_word_game', sa.String(length=64), nullable=True),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=False)
    op.create_index(op.f('ix_users_best_word_score'), 'users', ['best_word_score'], unique=False)
    op.create_index(op.f('ix_users_elo'), 'users', ['elo'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_highest_score'), 'users', ['highest_score'], unique=False)
    op.create_index(op.f('ix_users_human_elo'), 'users', ['human_elo'], unique=False)
    op.create_index('ix_users_locale_human_elo', 'users', ['locale', 'human_elo'], unique=False)
    op.create_index('ix_users_locale_name_lc', 'users', ['locale', 'name_lc'], unique=False)
    op.create_index('ix_users_locale_nick_lc', 'users', ['locale', 'nick_lc'], unique=False)
    op.create_index(op.f('ix_users_manual_elo'), 'users', ['manual_elo'], unique=False)
    op.create_index(op.f('ix_users_name_lc'), 'users', ['name_lc'], unique=False)
    op.create_index(op.f('ix_users_nick_lc'), 'users', ['nick_lc'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_table('blocks',
    sa.Column('blocker_id', sa.String(length=64), nullable=False),
    sa.Column('blocked_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_index('ix_blocks_blocked', 'blocks', ['blocked_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('src_user_id', sa.String(length=64), nullable=False),
    sa.Column('dest_user_id', sa.String(length=64), nullable=False),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dest_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_challenges_dest_ts', 'challenges', ['dest_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_challenges_dest_user_id'), 'challenges', ['dest_user_id'], unique=False)
    op.create_index('ix_challenges_src_dest', 'challenges', ['src_user_id', 'dest_user_id'], unique=False)
    op.create_index('ix_challenges_src_ts', 'challenges', ['src_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_challenges_src_user_id'), 'challenges', ['src_user_id'], unique=False)
    op.create_index(op.f('ix_challenges_timestamp'), 'challenges', ['timestamp'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=True),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_channel'), 'chats', ['channel'], unique=False)
    op.create_index('ix_chats_channel_ts', 'chats', ['channel', 'timestamp'], unique=False)
    op.create_index(op.f('ix_chats_recipient_id'), 'chats', ['recipient_id'], unique=False)
    op.create_index('ix_chats_recipient_ts', 'chats', ['recipient_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_chats_timestamp'), 'chats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index('ix_chats_user_ts', 'chats', ['user_id', 'timestamp'], unique=False)
    op.create_table('elo_ratings',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('human_elo', sa.Integer(), nullable=False),
    sa.Column('manual_elo', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'locale')
    )
    op.create_index(op.f('ix_elo_ratings_elo'), 'elo_ratings', ['elo'], unique=False)
    op.create_index(op.f('ix_elo_ratings_human_elo'), 'elo_ratings', ['human_elo'], unique=False)
    op.create_index('ix_elo_ratings_locale_elo', 'elo_ratings', ['locale', 'elo'], unique=False)
    op.create_index('ix_elo_ratings_locale_human_elo', 'elo_ratings', ['locale', 'human_elo'], unique=False)
    op.create_index('ix_elo_ratings_locale_manual_elo', 'elo_ratings', ['locale', 'manual_elo'], unique=False)
    op.create_index(op.f('ix_elo_ratings_manual_elo'), 'elo_ratings', ['manual_elo'], unique=False)
    op.create_table('favorites',
    sa.Column('src_user_id', sa.String(length=64), nullable=False),
    sa.Column('dest_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dest_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('src_user_id', 'dest_user_id')
    )
    op.create_index('ix_favorites_dest', 'favorites', ['dest_user_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('player0_id', sa.String(length=64), nullable=True),
    sa.Column('player1_id', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('rack0', sa.String(length=16), nullable=False),
    sa.Column('rack1', sa.String(length=16), nullable=False),
    sa.Column('irack0', sa.String(length=16), nullable=True),
    sa.Column('irack1', sa.String(length=16), nullable=True),
    sa.Column('score0', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('to_move', sa.Integer(), nullable=False),
    sa.Column('robot_level', sa.Integer(), nullable=False),
    sa.Column('over', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_last_move', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tile_count', sa.Integer(), nullable=True),
    sa.Column('elo0', sa.Integer(), nullable=True),
    sa.Column('elo1', sa.Integer(), nullable=True),
    sa.Column('elo0_adj', sa.Integer(), nullable=True),
    sa.Column('elo1_adj', sa.Integer(), nullable=True),
    sa.Column('human_elo0', sa.Integer(), nullable=True),
    sa.Column('human_elo1', sa.Integer(), nullable=True),
    sa.Column('human_elo0_adj', sa.Integer(), nullable=True),
    sa.Column('human_elo1_adj', sa.Integer(), nullable=True),
    sa.Column('manual_elo0', sa.Integer(), nullable=True),
    sa.Column('manual_elo1', sa.Integer(), nullable=True),
    sa.Column('manual_elo0_adj', sa.Integer(), nullable=True),
    sa.Column('manual_elo1_adj', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player0_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_over'), 'games', ['over'], unique=False)
    op.create_index('ix_games_over_ts', 'games', ['over', 'ts_last_move'], unique=False)
    op.create_index(op.f('ix_games_player0_id'), 'games', ['player0_id'], unique=False)
    op.create_index('ix_games_player0_over_ts', 'games', ['player0_id', 'over', 'ts_last_move'], unique=False)
    op.create_index(op.f('ix_games_player1_id'), 'games', ['player1_id'], unique=False)
    op.create_index('ix_games_player1_over_ts', 'games', ['player1_id', 'over', 'ts_last_move'], unique=False)
    op.create_index(op.f('ix_games_ts_last_move'), 'games', ['ts_last_move'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('fmt', sa.String(length=32), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_user_fmt', 'images', ['user_id', 'fmt'], unique=True)
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.create_table('promos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('promotion', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promos_promotion'), 'promos', ['promotion'], unique=False)
    op.create_index(op.f('ix_promos_timestamp'), 'promos', ['timestamp'], unique=False)
    op.create_index(op.f('ix_promos_user_id'), 'promos', ['user_id'], unique=False)
    op.create_index('ix_promos_user_promo_ts', 'promos', ['user_id', 'promotion', 'timestamp'], unique=False)
    op.create_table('ratings',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('robot_level', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_against', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('rank_yesterday', sa.Integer(), nullable=False),
    sa.Column('games_yesterday', sa.Integer(), nullable=False),
    sa.Column('elo_yesterday', sa.Integer(), nullable=False),
    sa.Column('score_yesterday', sa.Integer(), nullable=False),
    sa.Column('score_against_yesterday', sa.Integer(), nullable=False),
    sa.Column('wins_yesterday', sa.Integer(), nullable=False),
    sa.Column('losses_yesterday', sa.Integer(), nullable=False),
    sa.Column('rank_week_ago', sa.Integer(), nullable=False),
    sa.Column('games_week_ago', sa.Integer(), nullable=False),
    sa.Column('elo_week_ago', sa.Integer(), nullable=False),
    sa.Column('score_week_ago', sa.Integer(), nullable=False),
    sa.Column('score_against_week_ago', sa.Integer(), nullable=False),
    sa.Column('wins_week_ago', sa.Integer(), nullable=False),
    sa.Column('losses_week_ago', sa.Integer(), nullable=False),
    sa.Column('rank_month_ago', sa.Integer(), nullable=False),
    sa.Column('games_month_ago', sa.Integer(), nullable=False),
    sa.Column('elo_month_ago', sa.Integer(), nullable=False),
    sa.Column('score_month_ago', sa.Integer(), nullable=False),
    sa.Column('score_against_month_ago', sa.Integer(), nullable=False),
    sa.Column('wins_month_ago', sa.Integer(), nullable=False),
    sa.Column('losses_month_ago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('kind', 'rank')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reporter_id', sa.String(length=64), nullable=False),
    sa.Column('reported_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reported_id'), 'reports', ['reported_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_table('stats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('robot_level', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('human_games', sa.Integer(), nullable=False),
    sa.Column('manual_games', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('human_elo', sa.Integer(), nullable=False),
    sa.Column('manual_elo', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('human_score', sa.Integer(), nullable=False),
    sa.Column('manual_score', sa.Integer(), nullable=False),
    sa.Column('score_against', sa.Integer(), nullable=False),
    sa.Column('human_score_against', sa.Integer(), nullable=False),
    sa.Column('manual_score_against', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('human_wins', sa.Integer(), nullable=False),
    sa.Column('human_losses', sa.Integer(), nullable=False),
    sa.Column('manual_wins', sa.Integer(), nullable=False),
    sa.Column('manual_losses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_elo'), 'stats', ['elo'], unique=False)
    op.create_index(op.f('ix_stats_human_elo'), 'stats', ['human_elo'], unique=False)
    op.create_index(op.f('ix_stats_manual_elo'), 'stats', ['manual_elo'], unique=False)
    op.create_index(op.f('ix_stats_robot_level'), 'stats', ['robot_level'], unique=False)
    op.create_index(op.f('ix_stats_timestamp'), 'stats', ['timestamp'], unique=False)
    op.create_index(op.f('ix_stats_user_id'), 'stats', ['user_id'], unique=False)
    op.create_index('ix_stats_user_robot_ts', 'stats', ['user_id', 'robot_level', 'timestamp'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_ts'), 'submissions', ['ts'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_ts'), 'transactions', ['ts'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_ts', 'transactions', ['user_id', 'ts'], unique=False)
    op.create_table('zombies',
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zombies')
    op.drop_index('ix_transactions_user_ts', table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ts'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_ts'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_stats_user_robot_ts', table_name='stats')
    op.drop_index(op.f('ix_stats_user_id'), table_name='stats')
    op.drop_index(op.f('ix_stats_timestamp'), table_name='stats')
    op.drop_index(op.f('ix_stats_robot_level'), table_name='stats')
    op.drop_index(op.f('ix_stats_manual_elo'), table_name='stats')
    op.drop_index(op.f('ix_stats_human_elo'), table_name='stats')
    op.drop_index(op.f('ix_stats_elo'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('ratings')
    op.drop_index('ix_promos_user_promo_ts', table_name='promos')
    op.drop_index(op.f('ix_promos_user_id'), table_name='promos')
    op.drop_index(op.f('ix_promos_timestamp'), table_name='promos')
    op.drop_index(op.f('ix_promos_promotion'), table_name='promos')
    op.drop_table('promos')
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_index('ix_images_user_fmt', table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_games_ts_last_move'), table_name='games')
    op.drop_index('ix_games_player1_over_ts', table_name='games')
    op.drop_index(op.f('ix_games_player1_id'), table_name='games')
    op.drop_index('ix_games_player0_over_ts', table_name='games')
    op.drop_index(op.f('ix_games_player0_id'), table_name='games')
    op.drop_index('ix_games_over_ts', table_name='games')
    op.drop_index(op.f('ix_games_over'), table_name='games')
    op.drop_table('games')
    op.drop_index('ix_favorites_dest', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_elo_ratings_manual_elo'), table_name='elo_ratings')
    op.drop_index('ix_elo_ratings_locale_manual_elo', table_name='elo_ratings')
    op.drop_index('ix_elo_ratings_locale_human_elo', table_name='elo_ratings')
    op.drop_index('ix_elo_ratings_locale_elo', table_name='elo_ratings')
    op.drop_index(op.f('ix_elo_ratings_human_elo'), table_name='elo_ratings')
    op.drop_index(op.f('ix_elo_ratings_elo'), table_name='elo_ratings')
    op.drop_table('elo_ratings')
    op.drop_index('ix_chats_user_ts', table_name='chats')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_timestamp'), table_name='chats')
    op.drop_index('ix_chats_recipient_ts', table_name='chats')
    op.drop_index(op.f('ix_chats_recipient_id'), table_name='chats')
    op.drop_index('ix_chats_channel_ts', table_name='chats')
    op.drop_index(op.f('ix_chats_channel'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_challenges_timestamp'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_src_user_id'), table_name='challenges')
    op.drop_index('ix_challenges_src_ts', table_name='challenges')
    op.drop_index('ix_challenges_src_dest', table_name='challenges')
    op.drop_index(op.f('ix_challenges_dest_user_id'), table_name='challenges')
    op.drop_index('ix_challenges_dest_ts', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('ix_blocks_blocked', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_nick_lc'), table_name='users')
    op.drop_index(op.f('ix_users_name_lc'), table_name='users')
    op.drop_index(op.f('ix_users_manual_elo'), table_name='users')
    op.drop_index('ix_users_locale_nick_lc', table_name='users')
    op.drop_index('ix_users_locale_name_lc', table_name='users')
    op.drop_index('ix_users_locale_human_elo', table_name='users')
    op.drop_index(op.f('ix_users_human_elo'), table_name='users')
    op.drop_index(op.f('ix_users_highest_score'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_elo'), table_name='users')
    op.drop_index(op.f('ix_users_best_word_score'), table_name='users')
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.drop_table('users')
    op.drop_table('robots')
    op.drop_table('riddles')
    op.drop_table('rating_archive')
    op.drop_index(op.f('ix_completions_timestamp'), table_name='completions')
    op.drop_index(op.f('ix_completions_proctype'), table_name='completions')
    op.drop_table('completions')
    # ### end Alembic commands ###

