/*

  TypeScript declarations for Mithril.js and related functionality

  This file was originally auto-generated by tsc and then hand-tuned.

*/

export {
  m, Vnode, CustomVnode, VnodeAttrs,
  Component, ComponentFunc, EventHandler,
  MithrilEvent, MithrilDragEvent,
  VnodeChildren, RequestArgs
};

type mClass = string | typeof Link;

declare function m(cls: ComponentFunc<T>, attrs: T, children?: VnodeChildren): Vnode;
declare function m(cls: mClass, attrs: mAttrs, children: VnodeChildren): Vnode;
declare function m(cls: mClass, children: VnodeChildren): Vnode;
declare function m(cls: mClass, attrs: mAttrs): Vnode;
declare function m(cls: mClass): Vnode;

declare namespace m {
  export { render, request, redraw, jsonp, trust, fragment, mount };
  export { parseQueryString, buildQueryString };
  export { parsePathname, buildPathname };
  export { Vnode as vnode };
  export function route(root: HTMLElement, defaultRoute: string, routes: any): any;
  export namespace route {
    const SKIP: {};
    function set(path: string, data?: any, options?: any): void;
    function get(): any;
    const prefix: string;
    namespace Link {
      function view(vnode: any): any;
    }
    function param(key: string): string;
  }
}

declare function trust(html: string): Vnode;
declare function fragment(arg: {}, ...args: VnodeChildren): Vnode;
declare function mount(root: HTMLElement, component: ComponentFunc<T> | Component<T>): void;
declare function render(dom: HTMLElement, vnodes: VnodeChildren, redraw: boolean): void;
declare function redraw(): void;
declare namespace redraw {
  export function sync(): void;
}
declare function request(args: RequestArgs): Promise<any>;
declare function jsonp(url: string, args: any): any;
declare function parseQueryString(string: any): {};
declare function buildQueryString(object: any): string;
declare function parsePathname(url: string): {
  path: string;
  params: {};
};
declare function buildPathname(template: any, params: any): any;

interface RequestArgs {
  method: "GET" | "POST";
  url: string;
  body?: any;
  responseType?: string;
  deserialize?: (string) => string;
};

interface Vnode {
  tag: string;
  key: string;
  attrs: VnodeAttrs;
  children: Vnode[];
  text: any;
  dom: HTMLElement;
  domSize: any;
  state: any;
  events: any;
  instance: any;
  normalize: (node: any) => any;
  normalizeChildren: (input: any) => any;
}

interface MithrilEvent extends Event {
  redraw: boolean;
}

interface MithrilDragEvent extends DragEvent {
  redraw: boolean;
}

type EventHandler = (ev?: Event) => void;

// Mithril Vnode attributes
interface VnodeAttrs {
  // Common DOM event handlers
  onmouseover?: (ev?: MouseEvent) => void | boolean;
  onmouseout?: (ev?: MouseEvent) => void | boolean;
  onclick?: (ev?: MouseEvent) => void | boolean;
  onfocus?: EventHandler;
  oninput?: EventHandler;
  onkeypress?: (ev?: KeyboardEvent) => void;
  ondragstart?: (ev?: MithrilDragEvent) => void | boolean;
  ondragend?: (ev?: MithrilDragEvent) => void | boolean;
  ondragenter?: (ev?: MithrilDragEvent) => void | boolean;
  ondragleave?: (ev?: MithrilDragEvent) => void | boolean;
  ondragover?: (ev?: MithrilDragEvent) => void | boolean;
  ondrop?: (ev?: MithrilDragEvent) => void | boolean;
  // Mithril event handlers
  oninit?: (vnode: Vnode) => void;
  oncreate?: (vnode: Vnode) => void;
  onupdate?: (vnode: Vnode) => void;
  // Common HTML element attributes
  key?: string | number;
  class?: string;
  className?: string;
  id?: string;
  name?: string;
  style?: string | object;
  title?: string;
  tabindex?: number;
  autocomplete?: string;
  href?: string;
  src?: string;
  alt?: string;
  width?: number;
  height?: number;
  border?: number;
  type?: string;
  action?: string;
  method?: string;
  value?: string;
  initialValue?: string;
  checked?: boolean;
  disabled?: boolean;
  placeholder?: string;
  maxlength?: number;
  draggable?: string;
}

interface CustomVnode<T> extends Vnode {
  attrs: T;
}

interface Component<T> {
  view: (vnode: CustomVnode<T>) => m.vnode;
  oninit?: (vnode: CustomVnode<T>) => void;
  oncreate?: (vnode: CustomVnode<T>) => void;
  onupdate?: (vnode: CustomVnode<T>) => void;
  onremove?: (vnode: CustomVnode<T>) => void;
}

type ComponentFunc<T> = (vnode: CustomVnode<T>) => Component<T>;

type VnodeChildren = string | number | Vnode | VnodeChildren[];

type mAttrs = VnodeAttrs;
